"use strict";

// Byte-fidelity of the embedding templates against the OLD implementation.
//
// The fixtures were generated by running the original
// Portfolio-Stats-API/utils/embeddingGenerator.js (see
// scripts/generate-embedding-fixtures.js). If any assertion here fails, the new code
// would produce different vectors for the same input than the ones already sitting in
// Atlas — which degrades retrieval silently, with no error at read or write time.

const test = require("node:test");
const assert = require("node:assert/strict");

const {
  buildDocumentEmbeddingText,
  buildQueryEmbeddingText,
  truncateToChars,
} = require("../../src/documents/embeddings");

const fixtures = require("../fixtures/embedding-templates.json");

const MAX = fixtures.maxInputChars;

test("fixtures cover a truncation case", () => {
  const truncated = fixtures.documents.filter((f) => f.expected.length >= MAX - 200);
  assert.ok(truncated.length >= 1, "at least one document fixture must exercise truncation");
  assert.equal(fixtures.documents.length, 5);
  assert.equal(fixtures.queries.length, 5);
});

fixtures.documents.forEach(({ name, document, expected }) => {
  test(`document template is byte-identical: ${name}`, () => {
    const actual = buildDocumentEmbeddingText(document, MAX);

    assert.equal(actual.length, expected.length, "length differs");
    assert.equal(actual, expected);
  });
});

fixtures.queries.forEach(({ query, expected }, index) => {
  test(`query template is byte-identical: query ${index + 1}`, () => {
    const actual = buildQueryEmbeddingText(query, MAX);

    assert.equal(actual.length, expected.length, "length differs");
    assert.equal(actual, expected);
  });
});

// ---------------------------------------------------------------------------
// The rules the fixtures encode, asserted directly so a failure says which rule broke
// ---------------------------------------------------------------------------

test("document prefix and query prefix are exact", () => {
  assert.ok(buildDocumentEmbeddingText({ title: "T" }, MAX).startsWith("title: T | text: "));
  assert.ok(buildQueryEmbeddingText("q", MAX).startsWith("task: search result | query: "));
});

test("a blank or missing title becomes the literal 'none'", () => {
  assert.ok(buildDocumentEmbeddingText({}, MAX).startsWith("title: none | text: "));
  assert.ok(buildDocumentEmbeddingText({ title: "   " }, MAX).startsWith("title: none | text: "));
});

test("the Tags line is omitted entirely when there are no tags", () => {
  const withTags = buildDocumentEmbeddingText({ title: "T", tags: ["a", "b"], summary_for_embedding: "S" }, MAX);
  const without = buildDocumentEmbeddingText({ title: "T", tags: [], summary_for_embedding: "S" }, MAX);

  assert.equal(withTags, "title: T | text: Tags: a, b\nS");
  assert.equal(without, "title: T | text: S");
});

test("body parts join with a single newline, content last", () => {
  const text = buildDocumentEmbeddingText(
    { title: "T", tags: ["x"], summary_for_embedding: "S", content_full: "C" },
    MAX,
  );

  assert.equal(text, "title: T | text: Tags: x\nS\nC");
});

test("non-string tags are dropped rather than stringified", () => {
  const text = buildDocumentEmbeddingText({ title: "T", tags: ["a", null, 7, "  ", "b"] }, MAX);

  assert.equal(text, "title: T | text: Tags: a, b");
});

test("the budget shrinks as the title grows", () => {
  const short = buildDocumentEmbeddingText({ title: "T", content_full: "x".repeat(MAX) }, MAX);
  const long = buildDocumentEmbeddingText({ title: "T".repeat(50), content_full: "x".repeat(MAX) }, MAX);

  assert.equal(short.length, MAX);
  assert.equal(long.length, MAX);
  // Same total, so the longer title necessarily ate into the body.
  assert.ok(long.split(" | text: ")[1].length < short.split(" | text: ")[1].length);
});

test("truncation cuts at a word boundary past 0.8 of the budget, else hard", () => {
  // A space sits at index 90 of a 100-char budget: 90 > 80, so it is used.
  const wordy = `${"a".repeat(90)} ${"b".repeat(50)}`;
  assert.equal(truncateToChars(wordy, 100), "a".repeat(90));

  // A space at index 10 is below the threshold, so the hard cut wins.
  const early = `${"a".repeat(10)} ${"b".repeat(200)}`;
  assert.equal(truncateToChars(early, 100).length, 100);
});

test("truncation leaves short text completely untouched", () => {
  // Deliberately not trimmed on this path — the old code only trims after a cut.
  assert.equal(truncateToChars("short  ", 100), "short  ");
  assert.equal(truncateToChars("", 100), "");
  assert.equal(truncateToChars("anything", 0), "");
  assert.equal(truncateToChars("anything", -5), "");
});

test("a truncated result is right-trimmed", () => {
  // 130 chars, so truncation actually engages. The word-boundary cut lands inside the
  // run of spaces at index 89, and trimEnd removes what is left of them.
  const input = `${"a".repeat(85)}     ${"tail".repeat(10)}`;
  assert.ok(input.length > 100);

  assert.equal(truncateToChars(input, 100), "a".repeat(85));
});

test("queries are trimmed before the prefix is applied", () => {
  assert.equal(buildQueryEmbeddingText("   spaced   ", MAX), "task: search result | query: spaced");
  assert.equal(buildQueryEmbeddingText(null, MAX), "task: search result | query: ");
  assert.equal(buildQueryEmbeddingText(42, MAX), "task: search result | query: ");
});
