"use strict";

// Gemini embeddings, and the two prompt templates that decide what every vector in
// `moonmind_documents_v3` actually means.
//
// THE TEMPLATES ARE A WIRE FORMAT, NOT STYLE. Every vector already in Atlas was
// produced by the exact strings below. Changing a prefix, a separator or the 0.8
// word-boundary threshold changes the vector for the same input and silently degrades
// retrieval against the existing collection — no error, anywhere. They are carried over
// near-verbatim from the old `utils/embeddingGenerator.js` under the exception in
// ARCHITECTURE.md §3, and `test/documents/embedding-templates.test.js` pins them against
// fixtures generated by running that original code.

const { getConfig } = require("../config");

const RETRYABLE_STATUSES = new Set([408, 429, 500, 502, 503, 504]);

function embeddingError(message, status = null) {
  const error = new Error(message);
  // 429 is surfaced separately so callers (and the HTTP layer) can back off.
  error.code = status === 429 ? "RATE_LIMITED" : "EMBEDDING_FAILED";
  error.status = status;
  return error;
}

// ---------------------------------------------------------------------------
// Templates — byte-identical to the old implementation
// ---------------------------------------------------------------------------

/**
 * Truncate on a word boundary when one is reasonably close to the cut, so the model is
 * never fed a half-word. The 0.8 threshold is part of the contract.
 */
function truncateToChars(text, maxChars) {
  if (maxChars <= 0) {
    return "";
  }
  if (text.length <= maxChars) {
    return text;
  }

  const slice = text.slice(0, maxChars);
  const lastSpace = slice.lastIndexOf(" ");
  const cut = lastSpace > maxChars * 0.8 ? slice.slice(0, lastSpace) : slice;
  return cut.trimEnd();
}

/**
 * `title: <title> | text: <Tags: ...>\n<summary>\n<content_full>`
 *
 * Content goes last so overflow truncation trims its tail rather than dropping the tags
 * or the summary. The budget depends on the title's length — it is not a constant.
 */
function buildDocumentEmbeddingText(document = {}, maxInputChars) {
  const budgetTotal = maxInputChars ?? getConfig().gemini.maxInputChars;

  const title =
    typeof document.title === "string" && document.title.trim()
      ? document.title.trim()
      : "none";

  const tags = Array.isArray(document.tags)
    ? document.tags.filter((tag) => typeof tag === "string" && tag.trim())
    : [];

  const summary =
    typeof document.summary_for_embedding === "string"
      ? document.summary_for_embedding.trim()
      : "";

  const content =
    typeof document.content_full === "string" ? document.content_full.trim() : "";

  const body = [tags.length ? `Tags: ${tags.join(", ")}` : "", summary, content]
    .filter(Boolean)
    .join("\n");

  const prefix = `title: ${title} | text: `;
  return `${prefix}${truncateToChars(body, budgetTotal - prefix.length)}`;
}

/** `task: search result | query: <query>` — the asymmetric partner of the above. */
function buildQueryEmbeddingText(query, maxInputChars) {
  const budgetTotal = maxInputChars ?? getConfig().gemini.maxInputChars;
  const trimmed = typeof query === "string" ? query.trim() : "";
  const prefix = "task: search result | query: ";

  return `${prefix}${truncateToChars(trimmed, budgetTotal - prefix.length)}`;
}

// ---------------------------------------------------------------------------
// Gemini client
// ---------------------------------------------------------------------------

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

/** Server's Retry-After when present, else exponential backoff with full jitter. */
function backoffMs(attempt, retryAfterHeader, gemini) {
  const retryAfterSeconds = Number.parseFloat(retryAfterHeader);
  if (Number.isFinite(retryAfterSeconds) && retryAfterSeconds >= 0) {
    return Math.min(retryAfterSeconds * 1000, gemini.maxBackoffMs);
  }

  const exponential = gemini.retryBaseMs * 2 ** attempt;
  const jitter = Math.random() * gemini.retryBaseMs;
  return Math.min(exponential + jitter, gemini.maxBackoffMs);
}

async function requestEmbedding(text, gemini, fetchImpl) {
  const url = `${gemini.baseUrl}/v1beta/models/${gemini.model}:embedContent`;

  const response = await fetchImpl(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", "x-goog-api-key": gemini.apiKey },
    body: JSON.stringify({
      content: { parts: [{ text }] },
      output_dimensionality: gemini.dimensions,
    }),
    signal: AbortSignal.timeout(gemini.timeoutMs),
  });

  if (!response.ok) {
    const body = await response.text();
    const error = embeddingError(
      `Gemini embedding request failed: ${response.status} ${body.slice(0, 500)}`,
      response.status,
    );
    error.retryable = RETRYABLE_STATUSES.has(response.status);
    error.retryAfter = response.headers.get("retry-after");
    throw error;
  }

  return response.json();
}

/**
 * Embed a single text.
 *
 * ONE TEXT PER CALL, DELIBERATELY. Passing several inputs to `embedContent` returns one
 * aggregated vector rather than one per input — silently wrong rather than an error, so
 * every document would get the same blended vector. Never batch this.
 *
 * @param {string} text
 * @param {{ gemini?: object, fetchImpl?: Function }} [deps]
 */
async function embedText(text, deps = {}) {
  const gemini = deps.gemini ?? getConfig().gemini;
  const fetchImpl = deps.fetchImpl ?? fetch;

  if (typeof text !== "string" || text.trim().length === 0) {
    throw embeddingError("Embedding input must be a non-empty string");
  }
  if (!gemini.apiKey) {
    throw embeddingError("GEMINI_API_KEY is not configured");
  }

  let lastError = null;

  for (let attempt = 0; attempt <= gemini.maxRetries; attempt += 1) {
    try {
      const payload = await requestEmbedding(text, gemini, fetchImpl);
      const values = payload?.embedding?.values;

      if (!Array.isArray(values) || values.length === 0) {
        throw embeddingError("Gemini embedding response contained no vector");
      }
      // A wrong-length vector can never match the Atlas index. Fail here rather than
      // writing a document that is silently unsearchable forever.
      if (values.length !== gemini.dimensions) {
        throw embeddingError(
          `Gemini returned ${values.length} dimensions, expected ${gemini.dimensions}`,
        );
      }

      return values;
    } catch (error) {
      lastError = error;

      const isTimeout = error?.name === "TimeoutError" || error?.name === "AbortError";
      const retryable = error?.retryable === true || isTimeout;
      if (!retryable || attempt >= gemini.maxRetries) {
        break;
      }

      await sleep(backoffMs(attempt, error?.retryAfter, gemini));
    }
  }

  console.error("documents.embed.failed", {
    status: lastError?.status ?? null,
    message: lastError?.message,
  });

  if (lastError?.code === "RATE_LIMITED" || lastError?.code === "EMBEDDING_FAILED") {
    throw lastError;
  }
  throw embeddingError(`Gemini embedding failed: ${lastError?.message ?? "unknown error"}`);
}

/** Embed a stored document using the document template. */
async function embedDocument(document, deps = {}) {
  return embedText(buildDocumentEmbeddingText(document, deps.maxInputChars), deps);
}

/** Embed a search query using the query template. */
async function embedQuery(query, deps = {}) {
  return embedText(buildQueryEmbeddingText(query, deps.maxInputChars), deps);
}

module.exports = {
  truncateToChars,
  buildDocumentEmbeddingText,
  buildQueryEmbeddingText,
  embedText,
  embedDocument,
  embedQuery,
};
